### YamlMime:PythonEnum
uid: azure.mgmt.keyvault.models.Reason
name: Reason
fullName: azure.mgmt.keyvault.models.Reason
summary: 'The reason that a vault name could not be used. The Reason element is only
  returned if

  NameAvailable is false.'
module: azure.mgmt.keyvault.models
fields:
- name: ACCOUNT_NAME_INVALID
  uid: azure.mgmt.keyvault.models.Reason.ACCOUNT_NAME_INVALID
- name: ALREADY_EXISTS
  uid: azure.mgmt.keyvault.models.Reason.ALREADY_EXISTS
